### ISSUE TITLE
Have a version without the trackers

### ISSUE THREAD

**Issue by xRahul** [xRahul/FicsaveMiddleware#14]
fDroid compatible version without the trackers

**Comment by xRahul** [comment]
Created https://github.com/xRahul/FicsaveMiddleware/releases/tag/2.7.0

@IzzySoft Take a look

**Comment by IzzySoft** [comment]
You sure? According to [these gradle lines](https://github.com/xRahul/FicsaveMiddleware/blob/master/app/build.gradle#L37) it's still there (and you didn't touch the gradle).

Hm, strange. In the APK, it seems only GMS and Firebase is left – so I add it now (with AntiFeature again; [done](https://apt.izzysoft.de/fdroid/index/apk/in.rahulja.ficsavemiddleware) as soon as the sync is through). Are those two really needed? And why is the other stuff still listed in the gradle?

**Comment by xRahul** [comment]
I've actually created a separate branch for fDroid compatible code. master is as it is. I'll have to do more thorough change later, but this was a quick fix I made in the morning.

**Comment by IzzySoft** [comment]
Ah, there! Thanks for clarification!

If you finally want to bring it to the official repo, I need to check if our build recipes can specify a branch (and thus learn a new thing myself). But until then, there are two more things that must be removed: F-Droid doesn't accept Firebase nor GMS (for my repo, the two are considered AntiFeatures but not yet show-stoppers as for the official repo; though if you add another tracker to it (like it was before), I feel that too heavy as well; I'll probably do a cleanup in my repo for those apps already there with this combination).

OK, looking forward to your efforts concerning the remaining NonFree parts. Let me know when I shall help you bringing your apps to the official repo (when they're ready for it).

**Comment by xRahul** [comment]
I have removed the dependency to GMS and firebase core from the [gradle](https://github.com/xRahul/FicsaveMiddleware/blob/fDroid-compatible/app/build.gradle).
Only firebase-messaging is left which is required to send Push notifications to the user and is not related to tracking. Though, I think it comes under non-free dep. Let me also deep dive and see what I can do about it. I've seen someone mention Wire as replacement for FCM.

**Comment by IzzySoft** [comment]
FCM is also no-go for the official repo. There was a blog by/on Tutanota having implemented an alternative. No idea about Wire.

**Comment by xRahul** [comment]
Removed: https://github.com/xRahul/FicsaveMiddleware/releases/tag/2.7.1
Can you check if that removed the warning now?

**Comment by xRahul** [comment]
Also, a suggestion:
Create a badge for your repo that points to the URL where users can download the apk from or any other URL giving them access. I can then add the badge in readme.

**Comment by IzzySoft** [comment]
I'm no designer, so I cannot create a suitable badge. Some other devs "abuse" the F-Droid badge for that. Unless this could count, adapted from the original F-Droid badge:

![Get-it-on-IoD](https://apt.izzysoft.de/fdroid/get-it-on.png)

> Can you check if that removed the warning now?

Yes, it did – I just removed the AntiFeature (gets active tomorrow), thanks! So let me know when you want to try the official repo :wink:

**Comment by xRahul** [comment]
What's the official repo? I did once try to get these apps on fdroid, but there was too much hassle, and I also didn't want to remove the trackers at that time.
Let me see, I'll think on it.

**Comment by IzzySoft** [comment]
> What's the official repo? 

See: https://gitlab.com/fdroid/rfp (which is where "Requests For Packaging" are made for the official repo). The repo itself is at https://f-droid.org/
